[LRA-11] - Notification component
mkozachok/learn-react-app pull request #12
Opened 2019-12-13 17:25 UTC by KonstantinChabanenko

- antd styles were imported into App.css
- Were created sagas for success and error notifications
- Was used notification component from antd
- Notifications content was placed in separate file
- Interfaces for notifications objects were created

2019-12-13 19:28 UTC, mkozachok commented on src/store/sagas/notificationsSaga.ts
> +}
`function* successProductCreation(action) {
  yield notification.success(action.message);
}`

the message text should be passed from action

2019-12-16 14:41 UTC, KonstantinChabanenko commented on src/components/forms/UpdateProductForm/UpdateProductForm.tsx
> +          dispatch({ type: productActionTypes.UPDATE_PRODUCT__START });
temporary stub

2019-12-17 08:25 UTC, mkozachok requested changes

2019-12-17 08:25 UTC, mkozachok commented on src/store/sagas/notificationsSaga.ts
> +import { takeEvery } from 'redux-saga/effects';
maybe rename filename to productNotificationSagas.ts

2019-12-17 08:25 UTC, mkozachok commented on src/store/sagas/notificationsSaga.ts
> +  console.log("The product was deleted");
remove console.log()

2019-12-17 08:25 UTC, mkozachok commented on src/store/sagas/notificationsSaga.ts
> +function* successProductCreation() {
should end with `saga`

2019-12-17 08:25 UTC, mkozachok commented on src/resources/notifications.ts
> +const notifications: INotifications = {
think about separate by entity type - `productNotifications`, `orderNotification`, etc

2019-12-17 11:23 UTC, mkozachok approved these changes

2019-12-17 11:23 UTC, merged