[LRA-19] Login page template
mkozachok/learn-react-app pull request #21
Opened 2020-01-09 20:06 UTC by Shalin21

feat(Login page template): Create login template
feat(Formik): Create new types of field -
password and checkbox

Image:
![Screenshot 2020-01-09 at 22 05 10 (2)](https://user-images.githubusercontent.com/24594438/72100910-2f198280-332c-11ea-84f9-16aa68dc17e3.png)

2020-01-10 14:09 UTC, mkozachok requested changes

2020-01-10 14:09 UTC, mkozachok commented on src/Pages/Login/loginPage.tsx
> +export const loginPage = () => {
`export const loginPage = () =><LoginPageLayout />`

2020-01-10 14:09 UTC, mkozachok commented on src/components/forms/LoginForm/LoginForm.tsx
> +  const [isLoading, setIsLoading] = useState(false);
`setIsLoading` is not using

2020-01-10 14:09 UTC, mkozachok commented on src/components/forms/LoginForm/LoginForm.tsx
> +      <FormBlock></FormBlock>
Why we need this `<FormBlock></FormBlock>`

2020-01-10 14:09 UTC, mkozachok commented on src/components/forms/LoginForm/LoginForm.tsx
> +            <RowDiv>
Move to separate component

2020-01-13 12:24 UTC, Shalin21 commented on src/components/forms/LoginForm/LoginForm.tsx
> +      <FormBlock></FormBlock>
It's used for background

2020-01-13 12:26 UTC, Shalin21 commented on src/Pages/Login/loginPage.tsx
> +export const loginPage = () => {
Fixed

2020-01-13 12:26 UTC, Shalin21 commented on src/components/forms/LoginForm/LoginForm.tsx
> +  const [isLoading, setIsLoading] = useState(false);
Fixed

2020-01-13 12:26 UTC, Shalin21 commented on src/components/forms/LoginForm/LoginForm.tsx
> +            <RowDiv>
Done

2020-01-19 09:19 UTC, merged